apiVersion: v1
kind: Service
metadata:
  name: mysql-products
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql-products
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-products
spec:
  selector:
    matchLabels:
      app: mysql-products
  template:
    metadata:
      labels:
        app: mysql-products
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "product_db"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "password"
        ports:
        - containerPort: 3306
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost"]
          initialDelaySeconds: 5
          periodSeconds: 5
